### PR TITLE
Update german.js

### PR DESCRIPTION
**Pull request by sparksofinsanity**

### CODE REVIEW

**Comment by sparksofinsanity** [comment]
@the-j0k3r

is that enough with the help page or is there something missing?

**Comment by the-j0k3r** [comment]
this looks ok, but if you use the original format where language variables are reused it guarantees that any time strings change the help text will mostly remain the same.

And FYI thanks, this is really appreciated.

Ill merge but the comments above should be considered for general consistency sake.

**Comment by sparksofinsanity** [comment]
Well, the strings don't work quite right in German.

zusätzliche vs zusätzlichen

in english both is "additional"

**Comment by the-j0k3r** [comment]
Fair enough. Anyway merged here and awaiting upstream merge at https://github.com/mirror/dd-wrt/pull/264

Just have to wait for BS to be ready, real life and shit being what it is...

Thanks again. Fair warning, there's some of new help entries and a whole new help page  hstatus_inet.page1 on english.js which fits into HStatusWan.asp called from Status_Internet.asp where it previously called HStatus.asp which had help text for both Status_Router.asp page, So I separated both into each own around https://github.com/mirror/dd-wrt/pull/259/files

That would confuse even me, 

Just look for hstatus_inet.page1 anything else look at https://github.com/mirror/dd-wrt/pulls?q=is%3Apr+is%3Aclosed if interested.

Thanks for collaboration, this is how opensource should work I love Git for that reason only.

**Pull request merged**
